<a href="https://colab.research.google.com/github/makhti/-selfeducation/blob/master/Copy_of_%D0%90%D0%BF%D1%80%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%B8%D0%B9_%D0%BA%D1%83%D1%80%D1%81_2020_Light_Python_%D0%94%D0%BE%D0%BC%D0%B0%D1%88%D0%BD%D0%B5%D0%B5_%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Нейронные сети

## Домашнее задание 2. Numpy и функции

# Light

### Задача 1

1. Подгрузите файл **train_vector_1.csv** с помощью функции **np.loadtxt**. 

2. Назовите подгруженный массив my_array.

3. Убедитесь, что подгруженный массив имеет тип np.ndarray (выведите тип переменной my_array).

Ссылка на файл: https://drive.google.com/open?id=1ngnrhmoMInequrA6JyAe90lEPhcbi0iH

In [0]:
import numpy as np

In [199]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
my_array = np.loadtxt('/train_vector_1.csv', delimiter=',', skiprows=1)

In [201]:
type(my_array)
print(type(my_array))

<class 'numpy.ndarray'>


### Задача 2

Напишите код, который считает среднее значение всех элементов массива (без использования встроенных функций np.mean и т.д.). Для решения задачи воспользуйтесь циклом.
* С помощью команды %%timeit отобразите время выполнения написанного кода.
* Преобразуйте массив my_array в список (с помощью метода list()), сохраните его в переменной my_list.
* В новой ячейке посчитайте среднее значение всех элементов списка (воспользуйтесь тем же самым кодом, что и для массива).
* Командой %%timeit отобразите время выполнения и этой ячейки.

In [202]:
summa = 0
for i in range (my_array.size):
  summa += my_array [i]
x = summa/my_array.size
print(x)

3.0543624161073835


In [203]:
%%timeit n = 1
summa=0
for i in range(my_array.size):
  summa+=my_array [i]
x=summa/my_array.size

10000 loops, best of 3: 36.2 µs per loop


In [204]:
my_array = list (my_array)
my_array = my_list
print(my_list)

[3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3.0, 3.0, 4.0, 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3.0, 3.4, 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.6, 3.0, 3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3.0, 3.8, 3.2, 3.7, 3.3, 3.2, 3.2, 3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2.0, 3.0, 2.2, 2.9, 2.9, 3.1, 3.0, 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 2.8, 2.9, 3.0, 2.8, 3.0, 2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3.0, 3.4, 3.1, 2.3, 3.0, 2.5, 2.6, 3.0, 2.6, 2.3, 2.7, 3.0, 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3.0, 2.9, 3.0, 3.0, 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3.0, 2.5, 2.8, 3.2, 3.0, 3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3.0, 2.8, 3.0, 2.8, 3.8, 2.8, 2.8, 2.6, 3.0, 3.4, 3.1, 3.0, 3.1, 3.1, 3.1, 2.7, 3.2, 3.3, 3.0, 2.5, 3.0, 3.4, 3.0]


In [205]:
summa = 0
for i in range (len(my_list)):
  summa += my_list [i]
x = summa / len(my_list)
print(x)

3.0543624161073835


### Задача 3

Подгрузите файл **iris.csv** с помощью встроенной функции **np.loadtxt**. Назовите его my_2d_array. Напиишите код, который считает сумму элементов массива по столбцам (для решения данной задачи воспользуйтесь разделом ноутбук "Операции с двумерными массивами и встроенные методы").

In [0]:
import numpy as np

In [0]:
my_2d_array = np.loadtxt('/iris.csv', delimiter=',', skiprows=1)

In [208]:
print(my_2d_array.sum(axis=0))

[11175.    876.5   458.6   563.7   179.9]


### Задача 4 

* Используя библиотеку numpy, создайте массив 3x3, значения которого находятся в диапазоне от 11 до 40 (раздел "Семплирование из распределений"). 

* Не используя цикл for,  выведите на экран список элементов, которые меньше 20 (раздел "Индексация").

* Просуммируйте все элементы, не используя цикл for (раздел "Встроенные методы").


In [209]:
my_numpy_1 = np.random.randint(11, 40, (3,3))
print(my_numpy_1)

[[26 30 13]
 [18 31 23]
 [31 31 12]]


In [210]:
print(my_numpy_1 < 20)

[[False False  True]
 [ True False False]
 [False False  True]]


In [215]:
my_numpy_2 = np.array([26, 30, 13, 18, 31, 23, 31, 31, 12,]) 
print(my_numpy_2 < 20) 

[False False  True  True False False False False  True]


In [0]:
# print(my_numpy_1[my_numpy_1 < 20])

In [216]:
print(my_numpy_1.sum())

215


### Задача 5

* Создайте массив, который будет содержать списки с именем студента(str), его возрастом(int) и средней оценкой(float) (обратите внимание на пример с занятия со списком автомобильных регионов).
* Отсортируйте такой массив (обратите внимание на параметр order метода sort()).
* Замените значение, отвечающее за возраст, у всех студентов на одно и то же, например, 10. Отсортируйте такой массив. 

In [240]:
my_numpy_3 = [('student', '<U32'), ('age', np.int64), ('average mark', np.float32)]
values = [('Magomet',18,95), 
          ('Islam',17,93), 
          ('Khamzat',19,99)]
stobalniki_Dagestana = np.array(values, dtype = my_numpy_3) 
print(stobalniki_Dagestana) 

[('Magomet', 18, 95.) ('Islam', 17, 93.) ('Khamzat', 19, 99.)]


In [218]:
my_numpy_3 = [('student', '<U32'), ('age', np.int64), ('average mark', np.float32)]
my_numpy_3.sort()
print(my_numpy_3)

[('age', <class 'numpy.int64'>), ('average mark', <class 'numpy.float32'>), ('student', '<U32')]


In [243]:
my_numpy_3 = np.array([['Magomet',18,95], 
                       ['Islam',17,93], 
                       ['Khamzat',19,99]])
np.sort(stobalniki_Dagestana, order = 'age')

array([('Islam', 17, 93.), ('Magomet', 18, 95.), ('Khamzat', 19, 99.)],
      dtype=[('student', '<U32'), ('age', '<i8'), ('average mark', '<f4')])

In [245]:
# print(my_numpy_3)

[['Magomet' '18' '95']
 ['Islam' '17' '93']
 ['Khamzat' '19' '99']]


## Pro версия

### Задача 1

* Подгрузите массив **iris.csv** и назовите его my_array. 

* Создайте двумерный массив из случайных чисел той же размерности, что и my_array (раздел "Семплирование из распределений", потребуется использовать размерность массива my_array).

* Назовите его my_generated_array.

### Задача 2

* Выполните поэлементное умножение my_array на my_generated_array (раздел "векторные операции").

* Склейте массивы my_array, my_generated_array в один (могут помочь методы np.concatenate, np.vstack, np.hstack).

* Возьмите склеенный массив и разделите его на равные части (больше двух). Можно сделать вручную через циклы либо воспользоваться методом vsplit.

### Задача 3

* Найдите все элементы массива my_array, которые больше трех и меньше 5 одновременно. Используйте методологию подвыборки массива с условием (раздел "Индексация").

### Задача 4

Создайте трехмерный массив размера 2 на 3 на 4, состоящий из случайных ВЕЩЕСТВЕННЫХ чисел от 15 до 37. Используйте встроенные методы библиотеки  np.random.

### Задача 5

Используя массив из предыдущей задачи, преобразуйте его в новый массив со следующими значениями:

    * "small", если значения меньше 20
    * "medium", если значения в промежутке [20, 30]
    * "large", если значения больше 30

### Задача 6

Создайте одномерный массив из случайных 10 значений. 

* Не используя цикл for, найдите сумму значений с 3 по 7 элемент.
* Найдите сумму квадратов последних двух элементов.